# Generated by Django 3.2.3 on 2021-06-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Tipo de Mascota: ')),
                ('nomTipo', models.CharField(max_length=50, verbose_name='Nombre del Tipo de Mascota: ')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nroChip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Chip: ')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la Mascota: ')),
                ('dueno', models.CharField(max_length=30, verbose_name='Nombre del dueño de la Mascota: ')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediPets.tipomascota')),
            ],
        ),
    ]
