# Generated by Django 3.2.3 on 2021-06-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediPets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nroChip',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero de Chip: '),
        ),
    ]
